### ISSUE TITLE
Refinar o modelo de severidade e prioridade a ser utilizado no projeto

### ISSUE THREAD

**Issue by matheus-nantes** [antonioThomaz1903/trabalho-gcs#1]
No estado atual do projeto foi definido apenas superficialmente o modelo de severidade e prioridade a ser adotado no projeto, como pode ser visto no README do projeto, na branch "development", no commit 8c3aa6cd54ae90352ad0c35cfe59cb2dcdfa6a37:
![image](https://github.com/antonioThomaz1903/trabalho-gcs/assets/74730431/0af0b66c-f4a9-46b6-b758-0cead4b5617d)

Porém, é preciso que um modelo mais preciso e bem definido seja instituído para que de fato consigamos estabelecer e priorizar nossas issues de maneira adequada. 

Creio que uma abordagem adequada seria a seguinte:
Severidade:  critic, major, minor e enhancement
Prioridade: emergency, very urgent, urgent, routine.

Precisamos definir quais são os critérios e escopos que serão considerados para cada categorização de severidade e prioridade.
@LucasUlbrecht , @antonioThomaz1903 e @wa-lucao, quais são os escopos que vocês consideram de maior prioridade e/ou severidade no nosso projeto.

**Comment by wa-lucao** [comment]
Severidade
Crítica
   - Problemas que resultam em falhas críticas no sistema.
   - Perda significativa de dados.
   - Comprometimento da segurança de informações sensíveis.

Major
   - Impacto significativo nas funcionalidades do sistema.
   - Potencial para causar perda de dados, mas não catastrófica.
   - Degradação severa de desempenho.

Minor
   - Impacto em funcionalidades específicas sem causar falhas críticas.
   - Problemas menores que podem ser contornados.

Enhancement
   - Melhorias e ajustes que não afetam diretamente a funcionalidade do sistema.
   - Melhorias estéticas e de usabilidade.

Prioridade
Emergency
   - Requer ação imediata.
   - Problemas críticos que impedem o uso do sistema.

Very Urgent
   - Problemas que afetam funcionalidades importantes.
   - Necessitam de resolução rápida para evitar impactos maiores.

Urgent
   - Problemas que impactam funcionalidades secundárias.
   - Devem ser tratados dentro de um cronograma razoável.
  
Routine
   - Melhorias e problemas menores que podem ser resolvidos em momento oportuno.

Analisando o Projeto

Issues de Maior Prioridade e Severidade
Com base na análise do repositório, as áreas de maior prioridade e severidade incluem:

Segurança e Integridade dos Dados
   - Garantir que não haja vulnerabilidades de segurança.
   - Prevenir perda ou corrupção de dados.

Disponibilidade e Funcionalidade dos Endpoints
   - Manter os endpoints REST funcionando corretamente.
   - Garantir que consultas e envio de dados estejam operacionais.

Usuário Final e Experiência
   - Garantir que a interface seja intuitiva e responsiva.
   - Minimizar bugs que afetam diretamente o usuário final.

Implementação

Exemplo de Issue

Título: Falha Crítica no Endpoint de Consulta de Usuários
Severidade: Crítica
Prioridade: Emergency
Descrição:
O endpoint `/users` está retornando um erro 500, impedindo a consulta dos usuários cadastrados. Isso compromete a funcionalidade principal do sistema.

Passos para Resolver:
1. Verificar os logs para identificar a causa do erro.
2. Corrigir qualquer problema de conexão com o banco de dados.
3. Adicionar testes para garantir que o endpoint funcione corretamente.

Melhoria na Interface de Usuário
Severidade: Enhancement
Prioridade: Routine
Descrição:
Melhorar a responsividade e usabilidade da interface web utilizando Bootstrap.

Passos para Resolver:
1. Integrar o Bootstrap ao projeto.
2. Atualizar os componentes HTML para utilizar classes do Bootstrap.
3. Realizar testes de usabilidade.

Conclusão
Esses critérios ajudarão a priorizar e resolver issues de maneira eficaz, garantindo a estabilidade e usabilidade do sistema.

**Comment by antonioThomaz1903** [comment]
Acredito que seja necessário uma abordagem para o modelo de prioridade mais relacionada com a urgência do que com a criticidade. Desse modo, podemos nos preocupar mais com a agilidade com que desenvolvemos os mesmos.
Sugiro para o modelo de prioridade:
Emergência: prioridade máxima, deve ser concluído imediatamente
Muito urgente: prioridade alta, deve ser concluído com muita rapidez
Urgente: prioridade média, deve ser concluído rapidamente
Routineiro: prioridade baixa, equipe deve continuar seu ritmo normal para a conclusão

**Comment by matheus-nantes** [comment]
Eu e @antonioThomaz1903 já criamos as labels com a descrição conforme o especificado no primeiro comentário desta issue.

**Comment by matheus-nantes** [comment]
@LucasUlbrecht , @antonioThomaz1903 e @wa-lucao, vocês acham que será preciso colocar esta definição em um documento específico, ou deixamos a definição apenas no arquivo README.md?

**Comment by LucasUlbrecht** [comment]
Considerando que atualmente a grande demanda pela funcionalidade da API Gateway da aplicação que é adjunta da classe implantada "Newsletter" creio ser de interesse o foco nela durante a definição dos termos do modelo de prioridade. Me Apoiando no que foi descrito até o momento podemos usar o modelo:

Emergência: Problemas que representam uma interrupção crítica na comunicação do serviço Newsletter com clientes externos. Problemas que devem ser resolvidos imediatamente para evitar impactos significativos na operação da aplicação.

Muito Urgente: Questões que afetam diretamente a comunicação do serviço Newsletter com serviços externos de forma inadequada ou com falhas intermitentes. Esses problemas devem ser tratados com prioridade para garantir que a comunicação seja restaurada o mais rápido possível, mesmo que não cause uma interrupção completa.

Urgente: Problemas que não são críticos imediatamente, mas que ainda assim exigem uma solução rápida para evitar impactos negativos na experiência do usuário ou na eficiência operacional do serviço Newsletter.

Rotineiro: Questões de baixa prioridade que não têm urgência imediata e que podem ser tratadas dentro do fluxo de trabalho normal da equipe de desenvolvimento da aplicação. Geralmente envolvem melhorias incrementais, ajustes menores ou otimizações que não afetam diretamente a funcionalidade essencial.
 
 
 Rente a severidade podemos analisar falhas futuras e como elas atinjam o sistema, então o que foi dito como correto e manteria a base definida por @wa-lucao

**Comment by LucasUlbrecht** [comment]
Vamos incluir num documento separado para simplificar a leitura

**Comment by wa-lucao** [comment]
Concordo com as colocações apresentadas acima, creio que com a padronização, será muito melhor de organizar nossos processos durante a montagem do arquivo final.

**Comment by matheus-nantes** [comment]
OK, obrigado pelo feedback! Irei atualizar as definições no README.md

**Comment by matheus-nantes** [comment]
O modelo de severidade e prioridade foi especificado no arquivo README.md
