### ISSUE TITLE
Especificar periodicidade de notificação aos usuários

### ISSUE THREAD

**Issue by matheus-nantes** [antonioThomaz1903/trabalho-gcs#17]
Atualmente a entidade usuário possui apenas 4 atributos: id, usuário, email e senha. Os objetos dessa entidade são criados e salvos no banco de dados, e para o envio dos relatórios climáticos, são selecionados todos os usuários do banco, e para cada email e cada usuário, é enviado o relatório por email.
Porém, como definido na descrição e especificação de requisitos do projeto, é preciso que existam 4 tipos de periodicidade atribuída aos usuários, que pode assumir o valor de semanal, quinzenal, mensal e semestral. Contudo, na maneira que o sistema está implementado atualmente, é impossível implementar este requisito funcional, pois não existe um atributo no usuário para especificá-los, ou então uma segunda tabla para definir este atributo por meio de chaves estrangeiras. Como este é um dos requisitos que define a lógica principal do nosso sistema, que é justamente a geração de relatórios e envio dos mesmo por meio de e-mail, é de suma importância que isso seja resolvido de maneira eficaz e coerente com as necessidades do projeto.
Recomendo que seja adicionado o atributo "periodicidade" à entidade "Usuario", para que então os relatórios possam ser gerados e enviados aos usuários conforme o que foi escolhido pelo respectivo usuário.
@LucasUlbrecht e @wa-lucao, entrem em um consenso a respeito da melhor metodologia que vocês consideram que podemos resolver este problema e notifiquem por meio deste tópico

**Comment by LucasUlbrecht** [comment]
@wa-lucao creio que para solucionar isso necessariamente precisaremos ter tuplas para guardar um id de documento, dia de ultimo envio, a periodicidade e o status do ultimo envio. Quanto a onde incluir essas colunas imaginei duas formas, a primeira seria a inclusão dessas numa tabela a parte chamada DadosEnvio ou Usuario_Documento por exemplo aí teremos pouca preocupação de refatorar o banco completamente, e conseguimos separar esses dados numa área única, ou podemos estar incluindo tudo em usuário mesmo para padronizar a área de disposição da informação.
Estava pensando também referente a isso incluirmos uma função para salva numa tabela de log aparte mas isso creio que deve ser discutido mais a frente.
