### ISSUE TITLE
Adicionar um arquivo Composer Docker instanciação e inicialização padronizada de sistema

### ISSUE THREAD

**Issue by LucasUlbrecht** [antonioThomaz1903/trabalho-gcs#3]
Atualmente, é comum utilizar o Docker para facilitar a aplicação de projetos em múltiplos ambientes. No contexto atual, é de certa importância optarmos por essa abordagem. Recentemente, enfrentei um problema durante a instalação de bibliotecas na configuração atual, onde mesmo a instalando elas o Python não estava conseguindo reconhecer a biblioteca.

![Screenshot_19](https://github.com/antonioThomaz1903/trabalho-gcs/assets/98244995/272e32a0-16fd-4be2-8b9a-79594bb5d72f)

A forma de abordar seria criar um Dockerfile para instanciar projeto e suas bibliotecas e configurações no docker.

**Comment by matheus-nantes** [comment]
Acredito que seria a melhor abordagem, considerando que nosso sistema está se tornando cada vez maior e codependente de diferentes bibliotecas e versões. Precisaremos marcar uma reunião para alinhar quais serão as versões finais adotadas.

**Comment by matheus-nantes** [comment]
@antonioThomaz1903 , @LucasUlbrecht , @wa-lucao, vocês não acham que seria preciso incluir nos padrões de commit semântico as tags "style"(considerando que também estamos desenvolvendo uma UI) e "perf" (pois estamos trabalhando com banco de dados e grande fluxo de dados), concordam?
