### ISSUE TITLE
Criação de forma mais simples para se registrar no newsletter

### ISSUE THREAD

**Issue by wa-lucao** [antonioThomaz1903/trabalho-gcs#4]
Atualmente, para se cadastrar no newsletter, é necessário entrar no domínio e realizar o comando '/register', como não é algo intuitivo e irá gerar maiores dificuldades para usuário, deixo a aqui a necessidade da criação de um botão que realiza a ação desse comando, para viabilizar a inscrição e facilitar a entrada de novos usuários com menor praticidade com a área da informática.

**Comment by matheus-nantes** [comment]
Creio que teremos que implementar uma página de registro para que a funcionalidade de registro seja acessível para qualquer tipo de usuário, através da UI.
@wa-lucao, @LucasUlbrecht e @antonioThomaz1903 o que acham?

**Comment by antonioThomaz1903** [comment]
Nossa aplicação já possui uma interface de registro...
