### ISSUE TITLE
Falta de documentação do padrão dos commits semânticos

### ISSUE THREAD

**Issue by antonioThomaz1903** [antonioThomaz1903/trabalho-gcs#5]
# Commits Semânticos

Atualmente, nosso projeto possui muitos commits. Percebe-se pelos mesmos que os commits possuem certa padronização para torná-los semânticos e ser possível extrair mais informação útil sobre as alterações feitas. 

![image](https://github.com/antonioThomaz1903/trabalho-gcs/assets/132794484/f4b7646f-298d-45ee-bb6d-e9fab143f71f)

Entretanto, como novos desenvolvedores estão chegando ao projeto, torna-se necessário a documentação dos padrões dos commits para que o projeto não perca qualidade no quesito da gerência de mudanças.

Para resolver, @LucasUlbrecht @antonioThomaz1903 deverão incluir o padrão para os commits, incluindo-os no arquivo README.md

**Comment by LucasUlbrecht** [comment]
É de suma interesse analisarmos os commits semânticos já definidos e atualizarmos o documento mesmo

**Comment by LucasUlbrecht** [comment]
Rente ao que foi proposto a modelagem do documento não segue o padrão de agregado na listagem usada no .mb separado por "* " para identificação e separamento claro e detalhado

**Comment by matheus-nantes** [comment]
@antonioThomaz1903 , @LucasUlbrecht , @wa-lucao, vocês não acham que seria preciso incluir nos padrões de commit semântico as tags "style"(considerando que também estamos desenvolvendo uma UI) e "perf" (pois estamos trabalhando com banco de dados e grande fluxo de dados), concordam?
